name: test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: [ubuntu-latest, macos-latest]
          dub: dub
          code-coverage: |
            tlc=$(echo "$(cat -- *.lst)" | grep -E '^ *[0-9]+' | wc -l | xargs)
            elc=$(echo "$(cat -- *.lst)" | grep -E '^0000000'  | wc -l | xargs)
            echo code coverage: $(echo "scale=2;1-($elc/$tlc)" | bc)

        - os: windows-latest
          dub: dub.exe
          code-coverage: echo "code coverage not implemented for windows"
            

    steps:
      - uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@v1.0.3

      - name: Test
        run: ${{matrix.dub}} test --config=ci --coverage

      - name: Simple code coverage
        run: ${{matrix.code-coverage}}
